### ISSUE TITLE
Arquivo sobrando

### ISSUE THREAD

**Issue by sergiotp** [vmlellis/pragmatic_studio#1]
@vmlellis tem um arquivo de rspec_helper sobrando dentro dessa pasta:
https://github.com/vmlellis/pragmatic_studio/tree/master/ruby_22/lib/studio_game

Tem como arrumar ai e dar push? 

Valeu!!

**Comment by vmlellis** [comment]
@sergiotp Coloquei o rspec_helper para suprimir as mensagens de warning pois os exercícios estão na sintaxe do antigo RSpec.

Exemplo:

> foo.should eq(bar)

foi alterado para:

> expect(foo).to eq(bar)

Sugere outra solução?

**Comment by sergiotp** [comment]
@vmlellis acho q isso tem q estar dentro da pasta spec e não dentro da sua lib :)

**Comment by vmlellis** [comment]
@sergiotp Concordo! Foi corrigido. No exercício bonus utilizei a nova sintaxe do RSpec.
