### ISSUE TITLE
Problemas com indentação

### ISSUE THREAD

**Issue by sergiotp** [vmlellis/pragmatic_studio#3]
@vmlellis 

Tem problema de indentação nesses arquivos:
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_06.rb#L3
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_08.rb#L6-L7
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_08.rb#L11
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_08.rb#L15
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_09.rb#L11
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_09.rb#L18
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_09.rb#L35-L36
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_09.rb#L40
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_09.rb#L54
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_10.rb#L7-L8
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_10.rb#L12
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_10.rb#L26
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_10.rb#L33-L53
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_16/treasure_trove_spec.rb#L14 (falta um enter entre as linhas)
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_17/treasure_trove_spec.rb#L14 (falta um enter entre as linhas)

Da uma olhada nesse texto:
https://github.com/vmlellis/pragmatic_studio/blob/master/ruby_07.rb#L44 (lowercase está escrito errado).

valeu!

**Comment by vmlellis** [comment]
Corrigido!
